//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPEEDEAU.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class speedeau_mms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal speedeau_mms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPEEDEAU.Resources.speedeau.mms", typeof(speedeau_mms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSH-EC.
        /// </summary>
        internal static string EC {
            get {
                return ResourceManager.GetString("EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familles documents.
        /// </summary>
        internal static string Famille_Doc {
            get {
                return ResourceManager.GetString("Famille_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU.
        /// </summary>
        internal static string group_name {
            get {
                return ResourceManager.GetString("group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Metadata Service.
        /// </summary>
        internal static string mms_name {
            get {
                return ResourceManager.GetString("mms_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natures documents.
        /// </summary>
        internal static string Nature_Doc {
            get {
                return ResourceManager.GetString("Nature_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opération.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projets P＆S.
        /// </summary>
        internal static string Projets {
            get {
                return ResourceManager.GetString("Projets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acteurs P＆S.
        /// </summary>
        internal static string Redaction {
            get {
                return ResourceManager.GetString("Redaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartographie sites DPIH.
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thèmes documentaires.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
    }
}
