//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPEEDEAU.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class speedeau_core {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal speedeau_core() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPEEDEAU.Resources.speedeau.core", typeof(speedeau_core).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertes.
        /// </summary>
        internal static string Alertes_ListName {
            get {
                return ResourceManager.GetString("Alertes_ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertes Validation.
        /// </summary>
        internal static string Alertes_Validation_ListName {
            get {
                return ResourceManager.GetString("Alertes_Validation_ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déploiement.
        /// </summary>
        internal static string Deploiement_ListName {
            get {
                return ResourceManager.GetString("Deploiement_ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU.
        /// </summary>
        internal static string DiagnosticsArea {
            get {
                return ResourceManager.GetString("DiagnosticsArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU - Alertes.
        /// </summary>
        internal static string DiagnosticsArea_Alertes {
            get {
                return ResourceManager.GetString("DiagnosticsArea_Alertes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU - Application Page.
        /// </summary>
        internal static string DiagnosticsArea_ApplicationPage {
            get {
                return ResourceManager.GetString("DiagnosticsArea_ApplicationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU - Deploiement.
        /// </summary>
        internal static string DiagnosticsArea_Deploiement {
            get {
                return ResourceManager.GetString("DiagnosticsArea_Deploiement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU - Events.
        /// </summary>
        internal static string DiagnosticsArea_Events {
            get {
                return ResourceManager.GetString("DiagnosticsArea_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU - Features.
        /// </summary>
        internal static string DiagnosticsArea_Features {
            get {
                return ResourceManager.GetString("DiagnosticsArea_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU - Fields.
        /// </summary>
        internal static string DiagnosticsArea_Fields {
            get {
                return ResourceManager.GetString("DiagnosticsArea_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU - IIS.
        /// </summary>
        internal static string DiagnosticsArea_IIS {
            get {
                return ResourceManager.GetString("DiagnosticsArea_IIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU - Jobs.
        /// </summary>
        internal static string DiagnosticsArea_Job {
            get {
                return ResourceManager.GetString("DiagnosticsArea_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU - Observations.
        /// </summary>
        internal static string DiagnosticsArea_Observations {
            get {
                return ResourceManager.GetString("DiagnosticsArea_Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU - Other.
        /// </summary>
        internal static string DiagnosticsArea_Other {
            get {
                return ResourceManager.GetString("DiagnosticsArea_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU - Referentiel.
        /// </summary>
        internal static string DiagnosticsArea_Referentiel {
            get {
                return ResourceManager.GetString("DiagnosticsArea_Referentiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU - Security.
        /// </summary>
        internal static string DiagnosticsArea_Security {
            get {
                return ResourceManager.GetString("DiagnosticsArea_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU - Services.
        /// </summary>
        internal static string DiagnosticsArea_Services {
            get {
                return ResourceManager.GetString("DiagnosticsArea_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU - Webpart.
        /// </summary>
        internal static string DiagnosticsArea_WebPart {
            get {
                return ResourceManager.GetString("DiagnosticsArea_WebPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42010.
        /// </summary>
        internal static string Error_EventId {
            get {
                return ResourceManager.GetString("Error_EventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste de Suivi.
        /// </summary>
        internal static string ListeDeSuivi_ListName {
            get {
                return ResourceManager.GetString("ListeDeSuivi_ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations Déploiement.
        /// </summary>
        internal static string Observation_Deploiement_ListName {
            get {
                return ResourceManager.GetString("Observation_Deploiement_ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations Référentiel.
        /// </summary>
        internal static string Observation_Referentiel_ListName {
            get {
                return ResourceManager.GetString("Observation_Referentiel_ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Référentiel.
        /// </summary>
        internal static string Referentiel_ListName {
            get {
                return ResourceManager.GetString("Referentiel_ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU_ALERTE_CHECKBOX.
        /// </summary>
        internal static string WebPropertyBag_Alerte_CheckBox {
            get {
                return ResourceManager.GetString("WebPropertyBag_Alerte_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU_ALERTE_EMAIL.
        /// </summary>
        internal static string WebPropertyBag_Alerte_Email {
            get {
                return ResourceManager.GetString("WebPropertyBag_Alerte_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU_DEPLOIEMENT_FAMILLEDOC.
        /// </summary>
        internal static string WebPropertyBag_Deploiement_FamilleDoc {
            get {
                return ResourceManager.GetString("WebPropertyBag_Deploiement_FamilleDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU_PROJECT.
        /// </summary>
        internal static string WebPropertyBag_Project {
            get {
                return ResourceManager.GetString("WebPropertyBag_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU_REFERENTIEL_FAMILLEDOC.
        /// </summary>
        internal static string WebPropertyBag_Referentiel_FamilleDoc {
            get {
                return ResourceManager.GetString("WebPropertyBag_Referentiel_FamilleDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU_REGEX_CODIFCATION.
        /// </summary>
        internal static string WebPropertyBag_Regex_Codification {
            get {
                return ResourceManager.GetString("WebPropertyBag_Regex_Codification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEEDEAU_SITE_MSH_URL.
        /// </summary>
        internal static string WebPropertyBag_Site_Msh_Url {
            get {
                return ResourceManager.GetString("WebPropertyBag_Site_Msh_Url", resourceCulture);
            }
        }
    }
}
