//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPEEDEAU.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class speedeau_fields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal speedeau_fields() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPEEDEAU.Resources.speedeau.fields", typeof(speedeau_fields).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approbateur.
        /// </summary>
        internal static string approbateur {
            get {
                return ResourceManager.GetString("approbateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie de Document.
        /// </summary>
        internal static string CategorieDoc {
            get {
                return ResourceManager.GetString("CategorieDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codification.
        /// </summary>
        internal static string Codification {
            get {
                return ResourceManager.GetString("Codification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodificationSystem.
        /// </summary>
        internal static string CodificationSystem {
            get {
                return ResourceManager.GetString("CodificationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cible.
        /// </summary>
        internal static string Date_cible {
            get {
                return ResourceManager.GetString("Date_cible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format demandé.
        /// </summary>
        internal static string Format_demande {
            get {
                return ResourceManager.GetString("Format_demande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourniture.
        /// </summary>
        internal static string Fourniture {
            get {
                return ResourceManager.GetString("Fourniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice.
        /// </summary>
        internal static string Indice {
            get {
                return ResourceManager.GetString("Indice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTG Date.
        /// </summary>
        internal static string LIVRAISON_DATE_DTG {
            get {
                return ResourceManager.GetString("LIVRAISON_DATE_DTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploitant Date.
        /// </summary>
        internal static string LIVRAISON_DATE_EXPLOITANT {
            get {
                return ResourceManager.GetString("LIVRAISON_DATE_EXPLOITANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intégrateur Date.
        /// </summary>
        internal static string LIVRAISON_DATE_INTEGRATEUR {
            get {
                return ResourceManager.GetString("LIVRAISON_DATE_INTEGRATEUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCO Date.
        /// </summary>
        internal static string LIVRAISON_DATE_MCO {
            get {
                return ResourceManager.GetString("LIVRAISON_DATE_MCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableautier Date.
        /// </summary>
        internal static string LIVRAISON_DATE_TABLEAUTIER {
            get {
                return ResourceManager.GetString("LIVRAISON_DATE_TABLEAUTIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livr. DTG.
        /// </summary>
        internal static string LIVRAISON_DTG {
            get {
                return ResourceManager.GetString("LIVRAISON_DTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livr. Exploitant.
        /// </summary>
        internal static string LIVRAISON_EXPLOITANT {
            get {
                return ResourceManager.GetString("LIVRAISON_EXPLOITANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTG Format.
        /// </summary>
        internal static string LIVRAISON_FORMAT_DTG {
            get {
                return ResourceManager.GetString("LIVRAISON_FORMAT_DTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploitant Format.
        /// </summary>
        internal static string LIVRAISON_FORMAT_EXPLOITANT {
            get {
                return ResourceManager.GetString("LIVRAISON_FORMAT_EXPLOITANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intégrateur Format.
        /// </summary>
        internal static string LIVRAISON_FORMAT_INTEGRATEUR {
            get {
                return ResourceManager.GetString("LIVRAISON_FORMAT_INTEGRATEUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCO Format.
        /// </summary>
        internal static string LIVRAISON_FORMAT_MCO {
            get {
                return ResourceManager.GetString("LIVRAISON_FORMAT_MCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableautier Format.
        /// </summary>
        internal static string LIVRAISON_FORMAT_TABLEAUTIER {
            get {
                return ResourceManager.GetString("LIVRAISON_FORMAT_TABLEAUTIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livr. Intégrateur.
        /// </summary>
        internal static string LIVRAISON_INTEGRATEUR {
            get {
                return ResourceManager.GetString("LIVRAISON_INTEGRATEUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livr. MCO.
        /// </summary>
        internal static string LIVRAISON_MCO {
            get {
                return ResourceManager.GetString("LIVRAISON_MCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTG Stockage.
        /// </summary>
        internal static string LIVRAISON_STOCKAGE_DTG {
            get {
                return ResourceManager.GetString("LIVRAISON_STOCKAGE_DTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploitant Stockage.
        /// </summary>
        internal static string LIVRAISON_STOCKAGE_EXPLOITANT {
            get {
                return ResourceManager.GetString("LIVRAISON_STOCKAGE_EXPLOITANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intégrateur Stockage.
        /// </summary>
        internal static string LIVRAISON_STOCKAGE_INTEGRATEUR {
            get {
                return ResourceManager.GetString("LIVRAISON_STOCKAGE_INTEGRATEUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCO Stockage.
        /// </summary>
        internal static string LIVRAISON_STOCKAGE_MCO {
            get {
                return ResourceManager.GetString("LIVRAISON_STOCKAGE_MCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableautier Stockage.
        /// </summary>
        internal static string LIVRAISON_STOCKAGE_TABLEAUTIER {
            get {
                return ResourceManager.GetString("LIVRAISON_STOCKAGE_TABLEAUTIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livr. Tableautier.
        /// </summary>
        internal static string LIVRAISON_TABLEAUTIER {
            get {
                return ResourceManager.GetString("LIVRAISON_TABLEAUTIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        internal static string Observation {
            get {
                return ResourceManager.GetString("Observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation_rnvo.
        /// </summary>
        internal static string Observation_rnvo {
            get {
                return ResourceManager.GetString("Observation_rnvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opération.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process IH1600.
        /// </summary>
        internal static string ProcessIH1600 {
            get {
                return ResourceManager.GetString("ProcessIH1600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rédaction.
        /// </summary>
        internal static string redaction {
            get {
                return ResourceManager.GetString("redaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requis.
        /// </summary>
        internal static string Requis {
            get {
                return ResourceManager.GetString("Requis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reste à faire (h).
        /// </summary>
        internal static string reste_a_faire {
            get {
                return ResourceManager.GetString("reste_a_faire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Révision.
        /// </summary>
        internal static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Documentaire.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensemble cohérent.
        /// </summary>
        internal static string Taxon_EC {
            get {
                return ResourceManager.GetString("Taxon_EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famille documentaire.
        /// </summary>
        internal static string Taxon_FamilleDoc {
            get {
                return ResourceManager.GetString("Taxon_FamilleDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature documentaire.
        /// </summary>
        internal static string Taxon_NatureDoc {
            get {
                return ResourceManager.GetString("Taxon_NatureDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet.
        /// </summary>
        internal static string Taxon_Projet {
            get {
                return ResourceManager.GetString("Taxon_Projet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site DPIH.
        /// </summary>
        internal static string Taxon_Site {
            get {
                return ResourceManager.GetString("Taxon_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thème.
        /// </summary>
        internal static string Taxon_Theme {
            get {
                return ResourceManager.GetString("Taxon_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps estimé (h).
        /// </summary>
        internal static string temps_estime {
            get {
                return ResourceManager.GetString("temps_estime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validation avec observation.
        /// </summary>
        internal static string VAO {
            get {
                return ResourceManager.GetString("VAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérificateur.
        /// </summary>
        internal static string verificateur {
            get {
                return ResourceManager.GetString("verificateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérification.
        /// </summary>
        internal static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validation sans observation.
        /// </summary>
        internal static string VSO {
            get {
                return ResourceManager.GetString("VSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validation sans observation, sous condition.
        /// </summary>
        internal static string VSOSC {
            get {
                return ResourceManager.GetString("VSOSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validation sans observation, sans vérification.
        /// </summary>
        internal static string VSOSV {
            get {
                return ResourceManager.GetString("VSOSV", resourceCulture);
            }
        }
    }
}
