//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPEEDEAU.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class speedeau_validator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal speedeau_validator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPEEDEAU.Resources.speedeau.validator", typeof(speedeau_validator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom du fichier que vous avez sélectionné doit rester au même format que le précédent, à savoir :.
        /// </summary>
        internal static string ValidateFileUpload2 {
            get {
                return ResourceManager.GetString("ValidateFileUpload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez renommer ce fichier. ce nom existe déjà mais avec une codification différente..
        /// </summary>
        internal static string ValidateFileUpload3_1 {
            get {
                return ResourceManager.GetString("ValidateFileUpload3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un fichier du même nom existe déjà. Veuillez renommer ce fichier ou choisir le menu &apos;nouvelle version&apos;..
        /// </summary>
        internal static string ValidateFileUpload3_2 {
            get {
                return ResourceManager.GetString("ValidateFileUpload3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un fichier de même format existe déjà pour cette codification..
        /// </summary>
        internal static string ValidateFileUpload4 {
            get {
                return ResourceManager.GetString("ValidateFileUpload4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci de renseigner l&apos;indice pour une version BPE.
        /// </summary>
        internal static string ValidateIndice_1 {
            get {
                return ResourceManager.GetString("ValidateIndice_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci de renseigner l&apos;indice.
        /// </summary>
        internal static string ValidateIndice_2 {
            get {
                return ResourceManager.GetString("ValidateIndice_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez pas saisir un indice sans préciser le numéro de révision en version PREL.
        /// </summary>
        internal static string ValidateRevision {
            get {
                return ResourceManager.GetString("ValidateRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci de converser ou incrémenter la révision.
        /// </summary>
        internal static string ValidateRevisionIncrement_1 {
            get {
                return ResourceManager.GetString("ValidateRevisionIncrement_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le numéro de révision ne peut pas être inférieur ou égal à la version actuelle ({0}).
        /// </summary>
        internal static string ValidateRevisionIncrement_2 {
            get {
                return ResourceManager.GetString("ValidateRevisionIncrement_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un document BPE ne peut pas avoir numéro de de révision.
        /// </summary>
        internal static string ValidateRevisionIncrement_3 {
            get {
                return ResourceManager.GetString("ValidateRevisionIncrement_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci de renseigner le status documentaire du document.
        /// </summary>
        internal static string ValidateStatusDoc {
            get {
                return ResourceManager.GetString("ValidateStatusDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code saisi correspond à un document de la liste de suivi. Vous devez mettre à jour les propriétés correspondantes?.
        /// </summary>
        internal static string ValidateSuiviConsitency {
            get {
                return ResourceManager.GetString("ValidateSuiviConsitency", resourceCulture);
            }
        }
    }
}
